import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

import pluginValidateOffload  # noqa: E402


def test_ethtool_parse_stat() -> None:

    assert pluginValidateOffload.ethtool_stat_parse("") == {}

    data = """NIC statistics:
     tx_packets: 2537925
     rx_packets: 5645343
     tx_errors: 0
     rx_errors: 0
     rx_missed: 0
     align_errors: 0
     tx_single_collisions: 0
     tx_multi_collisions: 0
     rx_unicast: 5373570
     rx_broadcast: 226191
     rx_multicast: 45582
     tx_aborted: 0
     tx_underrun: 0
"""
    expected_d = {
        "tx_packets": "2537925",
        "rx_packets": "5645343",
        "tx_errors": "0",
        "rx_errors": "0",
        "rx_missed": "0",
        "align_errors": "0",
        "tx_single_collisions": "0",
        "tx_multi_collisions": "0",
        "rx_unicast": "5373570",
        "rx_broadcast": "226191",
        "rx_multicast": "45582",
        "tx_aborted": "0",
        "tx_underrun": "0",
    }

    d = pluginValidateOffload.ethtool_stat_parse(data)
    assert d == expected_d
    assert list(d) == list(expected_d)

    assert pluginValidateOffload.ethtool_stat_get_packets(d, "tx") == 2537925
    assert pluginValidateOffload.ethtool_stat_get_packets(d, "rx") == 5645343
    assert pluginValidateOffload.ethtool_stat_get_packets(d, "foo") is None

    res: dict[str, int] = {}
    assert pluginValidateOffload.ethtool_stat_get_startend(res, data, "start")
    assert res == {
        "rx_start": 5645343,
        "tx_start": 2537925,
    }
    assert pluginValidateOffload.ethtool_stat_get_startend(res, data, "end")
    assert res == {
        "rx_start": 5645343,
        "tx_start": 2537925,
        "rx_end": 5645343,
        "tx_end": 2537925,
    }


def test_ethtool_parse_stat_2() -> None:
    data1_start = """NIC statistics:
     peer_ifindex: 2
     rx_queue_0_xdp_packets: 0
     rx_queue_0_xdp_bytes: 0
     rx_queue_0_drops: 0
     rx_queue_0_xdp_redirect: 0
     rx_queue_0_xdp_drops: 0
     rx_queue_0_xdp_tx: 0
     rx_queue_0_xdp_tx_errors: 0
     rx_queue_1_xdp_packets: 2
     rx_queue_1_xdp_bytes: 112
     rx_queue_1_drops: 0
     rx_queue_1_xdp_redirect: 0
     rx_queue_1_xdp_drops: 0
     rx_queue_1_xdp_tx: 0
     rx_queue_1_xdp_tx_errors: 0
     rx_queue_2_xdp_packets: 0
     rx_queue_2_xdp_bytes: 0
     rx_queue_2_drops: 0
     rx_queue_2_xdp_redirect: 0
     rx_queue_2_xdp_drops: 0
     rx_queue_2_xdp_tx: 0
     rx_queue_2_xdp_tx_errors: 0
     rx_queue_3_xdp_packets: 0
     rx_queue_3_xdp_bytes: 0
     rx_queue_3_drops: 0
     rx_queue_3_xdp_redirect: 0
     rx_queue_3_xdp_drops: 0
     rx_queue_3_xdp_tx: 0
     rx_queue_3_xdp_tx_errors: 0
     rx_queue_4_xdp_packets: 0
     rx_queue_4_xdp_bytes: 0
     rx_queue_4_drops: 0
     rx_queue_4_xdp_redirect: 0
     rx_queue_4_xdp_drops: 0
     rx_queue_4_xdp_tx: 0
     rx_queue_4_xdp_tx_errors: 0
     rx_queue_5_xdp_packets: 0
     rx_queue_5_xdp_bytes: 0
     rx_queue_5_drops: 0
     rx_queue_5_xdp_redirect: 0
     rx_queue_5_xdp_drops: 0
     rx_queue_5_xdp_tx: 0
     rx_queue_5_xdp_tx_errors: 0
     rx_queue_6_xdp_packets: 1
     rx_queue_6_xdp_bytes: 72
     rx_queue_6_drops: 0
     rx_queue_6_xdp_redirect: 0
     rx_queue_6_xdp_drops: 0
     rx_queue_6_xdp_tx: 0
     rx_queue_6_xdp_tx_errors: 0
     rx_queue_7_xdp_packets: 0
     rx_queue_7_xdp_bytes: 0
     rx_queue_7_drops: 0
     rx_queue_7_xdp_redirect: 0
     rx_queue_7_xdp_drops: 0
     rx_queue_7_xdp_tx: 0
     rx_queue_7_xdp_tx_errors: 0
     rx_queue_8_xdp_packets: 0
     rx_queue_8_xdp_bytes: 0
     rx_queue_8_drops: 0
     rx_queue_8_xdp_redirect: 0
     rx_queue_8_xdp_drops: 0
     rx_queue_8_xdp_tx: 0
     rx_queue_8_xdp_tx_errors: 0
     rx_queue_9_xdp_packets: 2
     rx_queue_9_xdp_bytes: 152
     rx_queue_9_drops: 0
     rx_queue_9_xdp_redirect: 0
     rx_queue_9_xdp_drops: 0
     rx_queue_9_xdp_tx: 0
     rx_queue_9_xdp_tx_errors: 0
     rx_queue_10_xdp_packets: 0
     rx_queue_10_xdp_bytes: 0
     rx_queue_10_drops: 0
     rx_queue_10_xdp_redirect: 0
     rx_queue_10_xdp_drops: 0
     rx_queue_10_xdp_tx: 0
     rx_queue_10_xdp_tx_errors: 0
     rx_queue_11_xdp_packets: 0
     rx_queue_11_xdp_bytes: 0
     rx_queue_11_drops: 0
     rx_queue_11_xdp_redirect: 0
     rx_queue_11_xdp_drops: 0
     rx_queue_11_xdp_tx: 0
     rx_queue_11_xdp_tx_errors: 0
     rx_queue_12_xdp_packets: 0
     rx_queue_12_xdp_bytes: 0
     rx_queue_12_drops: 0
     rx_queue_12_xdp_redirect: 0
     rx_queue_12_xdp_drops: 0
     rx_queue_12_xdp_tx: 0
     rx_queue_12_xdp_tx_errors: 0
     rx_queue_13_xdp_packets: 0
     rx_queue_13_xdp_bytes: 0
     rx_queue_13_drops: 0
     rx_queue_13_xdp_redirect: 0
     rx_queue_13_xdp_drops: 0
     rx_queue_13_xdp_tx: 0
     rx_queue_13_xdp_tx_errors: 0
     rx_queue_14_xdp_packets: 0
     rx_queue_14_xdp_bytes: 0
     rx_queue_14_drops: 0
     rx_queue_14_xdp_redirect: 0
     rx_queue_14_xdp_drops: 0
     rx_queue_14_xdp_tx: 0
     rx_queue_14_xdp_tx_errors: 0
     rx_queue_15_xdp_packets: 0
     rx_queue_15_xdp_bytes: 0
     rx_queue_15_drops: 0
     rx_queue_15_xdp_redirect: 0
     rx_queue_15_xdp_drops: 0
     rx_queue_15_xdp_tx: 0
     rx_queue_15_xdp_tx_errors: 0
     rx_queue_16_xdp_packets: 0
     rx_queue_16_xdp_bytes: 0
     rx_queue_16_drops: 0
     rx_queue_16_xdp_redirect: 0
     rx_queue_16_xdp_drops: 0
     rx_queue_16_xdp_tx: 0
     rx_queue_16_xdp_tx_errors: 0
     rx_queue_17_xdp_packets: 0
     rx_queue_17_xdp_bytes: 0
     rx_queue_17_drops: 0
     rx_queue_17_xdp_redirect: 0
     rx_queue_17_xdp_drops: 0
     rx_queue_17_xdp_tx: 0
     rx_queue_17_xdp_tx_errors: 0
     rx_queue_18_xdp_packets: 0
     rx_queue_18_xdp_bytes: 0
     rx_queue_18_drops: 0
     rx_queue_18_xdp_redirect: 0
     rx_queue_18_xdp_drops: 0
     rx_queue_18_xdp_tx: 0
     rx_queue_18_xdp_tx_errors: 0
     rx_queue_19_xdp_packets: 0
     rx_queue_19_xdp_bytes: 0
     rx_queue_19_drops: 0
     rx_queue_19_xdp_redirect: 0
     rx_queue_19_xdp_drops: 0
     rx_queue_19_xdp_tx: 0
     rx_queue_19_xdp_tx_errors: 0
     rx_queue_20_xdp_packets: 0
     rx_queue_20_xdp_bytes: 0
     rx_queue_20_drops: 0
     rx_queue_20_xdp_redirect: 0
     rx_queue_20_xdp_drops: 0
     rx_queue_20_xdp_tx: 0
     rx_queue_20_xdp_tx_errors: 0
     rx_queue_21_xdp_packets: 2
     rx_queue_21_xdp_bytes: 152
     rx_queue_21_drops: 0
     rx_queue_21_xdp_redirect: 0
     rx_queue_21_xdp_drops: 0
     rx_queue_21_xdp_tx: 0
     rx_queue_21_xdp_tx_errors: 0
     rx_queue_22_xdp_packets: 0
     rx_queue_22_xdp_bytes: 0
     rx_queue_22_drops: 0
     rx_queue_22_xdp_redirect: 0
     rx_queue_22_xdp_drops: 0
     rx_queue_22_xdp_tx: 0
     rx_queue_22_xdp_tx_errors: 0
     rx_queue_23_xdp_packets: 0
     rx_queue_23_xdp_bytes: 0
     rx_queue_23_drops: 0
     rx_queue_23_xdp_redirect: 0
     rx_queue_23_xdp_drops: 0
     rx_queue_23_xdp_tx: 0
     rx_queue_23_xdp_tx_errors: 0
     rx_queue_24_xdp_packets: 0
     rx_queue_24_xdp_bytes: 0
     rx_queue_24_drops: 0
     rx_queue_24_xdp_redirect: 0
     rx_queue_24_xdp_drops: 0
     rx_queue_24_xdp_tx: 0
     rx_queue_24_xdp_tx_errors: 0
     rx_queue_25_xdp_packets: 0
     rx_queue_25_xdp_bytes: 0
     rx_queue_25_drops: 0
     rx_queue_25_xdp_redirect: 0
     rx_queue_25_xdp_drops: 0
     rx_queue_25_xdp_tx: 0
     rx_queue_25_xdp_tx_errors: 0
     rx_queue_26_xdp_packets: 0
     rx_queue_26_xdp_bytes: 0
     rx_queue_26_drops: 0
     rx_queue_26_xdp_redirect: 0
     rx_queue_26_xdp_drops: 0
     rx_queue_26_xdp_tx: 0
     rx_queue_26_xdp_tx_errors: 0
     rx_queue_27_xdp_packets: 0
     rx_queue_27_xdp_bytes: 0
     rx_queue_27_drops: 0
     rx_queue_27_xdp_redirect: 0
     rx_queue_27_xdp_drops: 0
     rx_queue_27_xdp_tx: 0
     rx_queue_27_xdp_tx_errors: 0
     rx_queue_28_xdp_packets: 0
     rx_queue_28_xdp_bytes: 0
     rx_queue_28_drops: 0
     rx_queue_28_xdp_redirect: 0
     rx_queue_28_xdp_drops: 0
     rx_queue_28_xdp_tx: 0
     rx_queue_28_xdp_tx_errors: 0
     rx_queue_29_xdp_packets: 0
     rx_queue_29_xdp_bytes: 0
     rx_queue_29_drops: 0
     rx_queue_29_xdp_redirect: 0
     rx_queue_29_xdp_drops: 0
     rx_queue_29_xdp_tx: 0
     rx_queue_29_xdp_tx_errors: 0
     rx_queue_30_xdp_packets: 0
     rx_queue_30_xdp_bytes: 0
     rx_queue_30_drops: 0
     rx_queue_30_xdp_redirect: 0
     rx_queue_30_xdp_drops: 0
     rx_queue_30_xdp_tx: 0
     rx_queue_30_xdp_tx_errors: 0
     rx_queue_31_xdp_packets: 0
     rx_queue_31_xdp_bytes: 0
     rx_queue_31_drops: 0
     rx_queue_31_xdp_redirect: 0
     rx_queue_31_xdp_drops: 0
     rx_queue_31_xdp_tx: 0
     rx_queue_31_xdp_tx_errors: 0
     rx_queue_32_xdp_packets: 0
     rx_queue_32_xdp_bytes: 0
     rx_queue_32_drops: 0
     rx_queue_32_xdp_redirect: 0
     rx_queue_32_xdp_drops: 0
     rx_queue_32_xdp_tx: 0
     rx_queue_32_xdp_tx_errors: 0
     rx_queue_33_xdp_packets: 0
     rx_queue_33_xdp_bytes: 0
     rx_queue_33_drops: 0
     rx_queue_33_xdp_redirect: 0
     rx_queue_33_xdp_drops: 0
     rx_queue_33_xdp_tx: 0
     rx_queue_33_xdp_tx_errors: 0
     rx_queue_34_xdp_packets: 0
     rx_queue_34_xdp_bytes: 0
     rx_queue_34_drops: 0
     rx_queue_34_xdp_redirect: 0
     rx_queue_34_xdp_drops: 0
     rx_queue_34_xdp_tx: 0
     rx_queue_34_xdp_tx_errors: 0
     rx_queue_35_xdp_packets: 0
     rx_queue_35_xdp_bytes: 0
     rx_queue_35_drops: 0
     rx_queue_35_xdp_redirect: 0
     rx_queue_35_xdp_drops: 0
     rx_queue_35_xdp_tx: 0
     rx_queue_35_xdp_tx_errors: 0
     rx_queue_36_xdp_packets: 0
     rx_queue_36_xdp_bytes: 0
     rx_queue_36_drops: 0
     rx_queue_36_xdp_redirect: 0
     rx_queue_36_xdp_drops: 0
     rx_queue_36_xdp_tx: 0
     rx_queue_36_xdp_tx_errors: 0
     rx_queue_37_xdp_packets: 0
     rx_queue_37_xdp_bytes: 0
     rx_queue_37_drops: 0
     rx_queue_37_xdp_redirect: 0
     rx_queue_37_xdp_drops: 0
     rx_queue_37_xdp_tx: 0
     rx_queue_37_xdp_tx_errors: 0
     rx_queue_38_xdp_packets: 0
     rx_queue_38_xdp_bytes: 0
     rx_queue_38_drops: 0
     rx_queue_38_xdp_redirect: 0
     rx_queue_38_xdp_drops: 0
     rx_queue_38_xdp_tx: 0
     rx_queue_38_xdp_tx_errors: 0
     rx_queue_39_xdp_packets: 0
     rx_queue_39_xdp_bytes: 0
     rx_queue_39_drops: 0
     rx_queue_39_xdp_redirect: 0
     rx_queue_39_xdp_drops: 0
     rx_queue_39_xdp_tx: 0
     rx_queue_39_xdp_tx_errors: 0
     rx_queue_40_xdp_packets: 0
     rx_queue_40_xdp_bytes: 0
     rx_queue_40_drops: 0
     rx_queue_40_xdp_redirect: 0
     rx_queue_40_xdp_drops: 0
     rx_queue_40_xdp_tx: 0
     rx_queue_40_xdp_tx_errors: 0
     rx_queue_41_xdp_packets: 0
     rx_queue_41_xdp_bytes: 0
     rx_queue_41_drops: 0
     rx_queue_41_xdp_redirect: 0
     rx_queue_41_xdp_drops: 0
     rx_queue_41_xdp_tx: 0
     rx_queue_41_xdp_tx_errors: 0
     rx_queue_42_xdp_packets: 0
     rx_queue_42_xdp_bytes: 0
     rx_queue_42_drops: 0
     rx_queue_42_xdp_redirect: 0
     rx_queue_42_xdp_drops: 0
     rx_queue_42_xdp_tx: 0
     rx_queue_42_xdp_tx_errors: 0
     rx_queue_43_xdp_packets: 0
     rx_queue_43_xdp_bytes: 0
     rx_queue_43_drops: 0
     rx_queue_43_xdp_redirect: 0
     rx_queue_43_xdp_drops: 0
     rx_queue_43_xdp_tx: 0
     rx_queue_43_xdp_tx_errors: 0
     rx_queue_44_xdp_packets: 0
     rx_queue_44_xdp_bytes: 0
     rx_queue_44_drops: 0
     rx_queue_44_xdp_redirect: 0
     rx_queue_44_xdp_drops: 0
     rx_queue_44_xdp_tx: 0
     rx_queue_44_xdp_tx_errors: 0
     rx_queue_45_xdp_packets: 0
     rx_queue_45_xdp_bytes: 0
     rx_queue_45_drops: 0
     rx_queue_45_xdp_redirect: 0
     rx_queue_45_xdp_drops: 0
     rx_queue_45_xdp_tx: 0
     rx_queue_45_xdp_tx_errors: 0
     rx_queue_46_xdp_packets: 0
     rx_queue_46_xdp_bytes: 0
     rx_queue_46_drops: 0
     rx_queue_46_xdp_redirect: 0
     rx_queue_46_xdp_drops: 0
     rx_queue_46_xdp_tx: 0
     rx_queue_46_xdp_tx_errors: 0
     rx_queue_47_xdp_packets: 0
     rx_queue_47_xdp_bytes: 0
     rx_queue_47_drops: 0
     rx_queue_47_xdp_redirect: 0
     rx_queue_47_xdp_drops: 0
     rx_queue_47_xdp_tx: 0
     rx_queue_47_xdp_tx_errors: 0
     rx_queue_48_xdp_packets: 0
     rx_queue_48_xdp_bytes: 0
     rx_queue_48_drops: 0
     rx_queue_48_xdp_redirect: 0
     rx_queue_48_xdp_drops: 0
     rx_queue_48_xdp_tx: 0
     rx_queue_48_xdp_tx_errors: 0
     rx_queue_49_xdp_packets: 0
     rx_queue_49_xdp_bytes: 0
     rx_queue_49_drops: 0
     rx_queue_49_xdp_redirect: 0
     rx_queue_49_xdp_drops: 0
     rx_queue_49_xdp_tx: 0
     rx_queue_49_xdp_tx_errors: 0
     rx_queue_50_xdp_packets: 0
     rx_queue_50_xdp_bytes: 0
     rx_queue_50_drops: 0
     rx_queue_50_xdp_redirect: 0
     rx_queue_50_xdp_drops: 0
     rx_queue_50_xdp_tx: 0
     rx_queue_50_xdp_tx_errors: 0
     rx_queue_51_xdp_packets: 0
     rx_queue_51_xdp_bytes: 0
     rx_queue_51_drops: 0
     rx_queue_51_xdp_redirect: 0
     rx_queue_51_xdp_drops: 0
     rx_queue_51_xdp_tx: 0
     rx_queue_51_xdp_tx_errors: 0
     rx_queue_52_xdp_packets: 0
     rx_queue_52_xdp_bytes: 0
     rx_queue_52_drops: 0
     rx_queue_52_xdp_redirect: 0
     rx_queue_52_xdp_drops: 0
     rx_queue_52_xdp_tx: 0
     rx_queue_52_xdp_tx_errors: 0
     rx_queue_53_xdp_packets: 0
     rx_queue_53_xdp_bytes: 0
     rx_queue_53_drops: 0
     rx_queue_53_xdp_redirect: 0
     rx_queue_53_xdp_drops: 0
     rx_queue_53_xdp_tx: 0
     rx_queue_53_xdp_tx_errors: 0
     rx_queue_54_xdp_packets: 0
     rx_queue_54_xdp_bytes: 0
     rx_queue_54_drops: 0
     rx_queue_54_xdp_redirect: 0
     rx_queue_54_xdp_drops: 0
     rx_queue_54_xdp_tx: 0
     rx_queue_54_xdp_tx_errors: 0
     rx_queue_55_xdp_packets: 0
     rx_queue_55_xdp_bytes: 0
     rx_queue_55_drops: 0
     rx_queue_55_xdp_redirect: 0
     rx_queue_55_xdp_drops: 0
     rx_queue_55_xdp_tx: 0
     rx_queue_55_xdp_tx_errors: 0
     rx_queue_56_xdp_packets: 0
     rx_queue_56_xdp_bytes: 0
     rx_queue_56_drops: 0
     rx_queue_56_xdp_redirect: 0
     rx_queue_56_xdp_drops: 0
     rx_queue_56_xdp_tx: 0
     rx_queue_56_xdp_tx_errors: 0
     rx_queue_57_xdp_packets: 0
     rx_queue_57_xdp_bytes: 0
     rx_queue_57_drops: 0
     rx_queue_57_xdp_redirect: 0
     rx_queue_57_xdp_drops: 0
     rx_queue_57_xdp_tx: 0
     rx_queue_57_xdp_tx_errors: 0
     rx_queue_58_xdp_packets: 0
     rx_queue_58_xdp_bytes: 0
     rx_queue_58_drops: 0
     rx_queue_58_xdp_redirect: 0
     rx_queue_58_xdp_drops: 0
     rx_queue_58_xdp_tx: 0
     rx_queue_58_xdp_tx_errors: 0
     rx_queue_59_xdp_packets: 0
     rx_queue_59_xdp_bytes: 0
     rx_queue_59_drops: 0
     rx_queue_59_xdp_redirect: 0
     rx_queue_59_xdp_drops: 0
     rx_queue_59_xdp_tx: 0
     rx_queue_59_xdp_tx_errors: 0
     rx_queue_60_xdp_packets: 0
     rx_queue_60_xdp_bytes: 0
     rx_queue_60_drops: 0
     rx_queue_60_xdp_redirect: 0
     rx_queue_60_xdp_drops: 0
     rx_queue_60_xdp_tx: 0
     rx_queue_60_xdp_tx_errors: 0
     rx_queue_61_xdp_packets: 0
     rx_queue_61_xdp_bytes: 0
     rx_queue_61_drops: 0
     rx_queue_61_xdp_redirect: 0
     rx_queue_61_xdp_drops: 0
     rx_queue_61_xdp_tx: 0
     rx_queue_61_xdp_tx_errors: 0
     rx_queue_62_xdp_packets: 0
     rx_queue_62_xdp_bytes: 0
     rx_queue_62_drops: 0
     rx_queue_62_xdp_redirect: 0
     rx_queue_62_xdp_drops: 0
     rx_queue_62_xdp_tx: 0
     rx_queue_62_xdp_tx_errors: 0
     rx_queue_63_xdp_packets: 0
     rx_queue_63_xdp_bytes: 0
     rx_queue_63_drops: 0
     rx_queue_63_xdp_redirect: 0
     rx_queue_63_xdp_drops: 0
     rx_queue_63_xdp_tx: 0
     rx_queue_63_xdp_tx_errors: 0
     tx_queue_0_xdp_xmit: 0
     tx_queue_0_xdp_xmit_errors: 0
"""
    data2_start = """NIC statistics:
     peer_ifindex: 2
     rx_queue_0_xdp_packets: 0
     rx_queue_0_xdp_bytes: 0
     rx_queue_0_drops: 0
     rx_queue_0_xdp_redirect: 0
     rx_queue_0_xdp_drops: 0
     rx_queue_0_xdp_tx: 0
     rx_queue_0_xdp_tx_errors: 0
     rx_queue_1_xdp_packets: 0
     rx_queue_1_xdp_bytes: 0
     rx_queue_1_drops: 0
     rx_queue_1_xdp_redirect: 0
     rx_queue_1_xdp_drops: 0
     rx_queue_1_xdp_tx: 0
     rx_queue_1_xdp_tx_errors: 0
     rx_queue_2_xdp_packets: 0
     rx_queue_2_xdp_bytes: 0
     rx_queue_2_drops: 0
     rx_queue_2_xdp_redirect: 0
     rx_queue_2_xdp_drops: 0
     rx_queue_2_xdp_tx: 0
     rx_queue_2_xdp_tx_errors: 0
     rx_queue_3_xdp_packets: 0
     rx_queue_3_xdp_bytes: 0
     rx_queue_3_drops: 0
     rx_queue_3_xdp_redirect: 0
     rx_queue_3_xdp_drops: 0
     rx_queue_3_xdp_tx: 0
     rx_queue_3_xdp_tx_errors: 0
     rx_queue_4_xdp_packets: 0
     rx_queue_4_xdp_bytes: 0
     rx_queue_4_drops: 0
     rx_queue_4_xdp_redirect: 0
     rx_queue_4_xdp_drops: 0
     rx_queue_4_xdp_tx: 0
     rx_queue_4_xdp_tx_errors: 0
     rx_queue_5_xdp_packets: 0
     rx_queue_5_xdp_bytes: 0
     rx_queue_5_drops: 0
     rx_queue_5_xdp_redirect: 0
     rx_queue_5_xdp_drops: 0
     rx_queue_5_xdp_tx: 0
     rx_queue_5_xdp_tx_errors: 0
     rx_queue_6_xdp_packets: 0
     rx_queue_6_xdp_bytes: 0
     rx_queue_6_drops: 0
     rx_queue_6_xdp_redirect: 0
     rx_queue_6_xdp_drops: 0
     rx_queue_6_xdp_tx: 0
     rx_queue_6_xdp_tx_errors: 0
     rx_queue_7_xdp_packets: 0
     rx_queue_7_xdp_bytes: 0
     rx_queue_7_drops: 0
     rx_queue_7_xdp_redirect: 0
     rx_queue_7_xdp_drops: 0
     rx_queue_7_xdp_tx: 0
     rx_queue_7_xdp_tx_errors: 0
     rx_queue_8_xdp_packets: 0
     rx_queue_8_xdp_bytes: 0
     rx_queue_8_drops: 0
     rx_queue_8_xdp_redirect: 0
     rx_queue_8_xdp_drops: 0
     rx_queue_8_xdp_tx: 0
     rx_queue_8_xdp_tx_errors: 0
     rx_queue_9_xdp_packets: 0
     rx_queue_9_xdp_bytes: 0
     rx_queue_9_drops: 0
     rx_queue_9_xdp_redirect: 0
     rx_queue_9_xdp_drops: 0
     rx_queue_9_xdp_tx: 0
     rx_queue_9_xdp_tx_errors: 0
     rx_queue_10_xdp_packets: 0
     rx_queue_10_xdp_bytes: 0
     rx_queue_10_drops: 0
     rx_queue_10_xdp_redirect: 0
     rx_queue_10_xdp_drops: 0
     rx_queue_10_xdp_tx: 0
     rx_queue_10_xdp_tx_errors: 0
     rx_queue_11_xdp_packets: 2
     rx_queue_11_xdp_bytes: 152
     rx_queue_11_drops: 0
     rx_queue_11_xdp_redirect: 0
     rx_queue_11_xdp_drops: 0
     rx_queue_11_xdp_tx: 0
     rx_queue_11_xdp_tx_errors: 0
     rx_queue_12_xdp_packets: 1
     rx_queue_12_xdp_bytes: 72
     rx_queue_12_drops: 0
     rx_queue_12_xdp_redirect: 0
     rx_queue_12_xdp_drops: 0
     rx_queue_12_xdp_tx: 0
     rx_queue_12_xdp_tx_errors: 0
     rx_queue_13_xdp_packets: 0
     rx_queue_13_xdp_bytes: 0
     rx_queue_13_drops: 0
     rx_queue_13_xdp_redirect: 0
     rx_queue_13_xdp_drops: 0
     rx_queue_13_xdp_tx: 0
     rx_queue_13_xdp_tx_errors: 0
     rx_queue_14_xdp_packets: 0
     rx_queue_14_xdp_bytes: 0
     rx_queue_14_drops: 0
     rx_queue_14_xdp_redirect: 0
     rx_queue_14_xdp_drops: 0
     rx_queue_14_xdp_tx: 0
     rx_queue_14_xdp_tx_errors: 0
     rx_queue_15_xdp_packets: 0
     rx_queue_15_xdp_bytes: 0
     rx_queue_15_drops: 0
     rx_queue_15_xdp_redirect: 0
     rx_queue_15_xdp_drops: 0
     rx_queue_15_xdp_tx: 0
     rx_queue_15_xdp_tx_errors: 0
     rx_queue_16_xdp_packets: 0
     rx_queue_16_xdp_bytes: 0
     rx_queue_16_drops: 0
     rx_queue_16_xdp_redirect: 0
     rx_queue_16_xdp_drops: 0
     rx_queue_16_xdp_tx: 0
     rx_queue_16_xdp_tx_errors: 0
     rx_queue_17_xdp_packets: 0
     rx_queue_17_xdp_bytes: 0
     rx_queue_17_drops: 0
     rx_queue_17_xdp_redirect: 0
     rx_queue_17_xdp_drops: 0
     rx_queue_17_xdp_tx: 0
     rx_queue_17_xdp_tx_errors: 0
     rx_queue_18_xdp_packets: 0
     rx_queue_18_xdp_bytes: 0
     rx_queue_18_drops: 0
     rx_queue_18_xdp_redirect: 0
     rx_queue_18_xdp_drops: 0
     rx_queue_18_xdp_x: 0
     rx_queue_18_xdp_tx_errors: 0
     rx_queue_19_xdp_packets: 0
     rx_queue_19_xdp_bytes: 0
     rx_queue_19_drops: 0
     rx_queue_19_xdp_redirect: 0
     rx_queue_19_xdp_drops: 0
     rx_queue_19_xdp_tx: 0
     rx_queue_19_xdp_tx_errors: 0
     rx_queue_20_xdp_packets: 0
     rx_queue_20_xdp_bytes: 0
     rx_queue_20_drops: 0
     rx_queue_20_xdp_redirect: 0
     rx_queue_20_xdp_drops: 0
     rx_queue_20_xdp_tx: 0
     rx_queue_20_xdp_tx_errors: 0
     rx_queue_21_xdp_packets: 2
     rx_queue_21_xdp_bytes: 152
     rx_queue_21_drops: 0
     rx_queue_21_xdp_redirect: 0
     rx_queue_21_xdp_drops: 0
     rx_queue_21_xdp_tx: 0
     rx_queue_21_xdp_tx_errors: 0
     rx_queue_22_xdp_packets: 0
     rx_queue_22_xdp_bytes: 0
     rx_queue_22_drops: 0
     rx_queue_22_xdp_redirect: 0
     rx_queue_22_xdp_drops: 0
     rx_queue_22_xdp_tx: 0
     rx_queue_22_xdp_tx_errors: 0
     rx_queue_23_xdp_packets: 0
     rx_queue_23_xdp_bytes: 0
     rx_queue_23_drops: 0
     rx_queue_23_xdp_redirect: 0
     rx_queue_23_xdp_drops: 0
     rx_queue_23_xdp_tx: 0
     rx_queue_23_xdp_tx_errors: 0
     rx_queue_24_xdp_packets: 0
     rx_queue_24_xdp_bytes: 0
     rx_queue_24_drops: 0
     rx_queue_24_xdp_redirect: 0
     rx_queue_24_xdp_drops: 0
     rx_queue_24_xdp_tx: 0
     rx_queue_24_xdp_tx_errors: 0
     rx_queue_25_xdp_packets: 0
     rx_queue_25_xdp_bytes: 0
     rx_queue_25_drops: 0
     rx_queue_25_xdp_redirect: 0
     rx_queue_25_xdp_drops: 0
     rx_queue_25_xdp_tx: 0
     rx_queue_25_xdp_tx_errors: 0
     rx_queue_26_xdp_packets: 0
     rx_queue_26_xdp_bytes: 0
     rx_queue_26_drops: 0
     rx_queue_26_xdp_redirect: 0
     rx_queue_26_xdp_drops: 0
     rx_queue_26_xdp_tx: 0
     rx_queue_26_xdp_tx_errors: 0
     rx_queue_27_xdp_packets: 0
     rx_queue_27_xdp_bytes: 0
     rx_queue_27_drops: 0
     rx_queue_27_xdp_redirect: 0
     rx_queue_27_xdp_drops: 0
     rx_queue_27_xdp_tx: 0
     rx_queue_27_xdp_tx_errors: 0
     rx_queue_28_xdp_packets: 0
     rx_queue_28_xdp_bytes: 0
     rx_queue_28_drops: 0
     rx_queue_28_xdp_redirect: 0
     rx_queue_28_xdp_drops: 0
     rx_queue_28_xdp_tx: 0
     rx_queue_28_xdp_tx_errors: 0
     rx_queue_29_xdp_packets: 0
     rx_queue_29_xdp_bytes: 0
     rx_queue_29_drops: 0
     rx_queue_29_xdp_redirect: 0
     rx_queue_29_xdp_drops: 0
     rx_queue_29_xdp_tx: 0
     rx_queue_29_xdp_tx_errors: 0
     rx_queue_30_xdp_packets: 0
     rx_queue_30_xdp_bytes: 0
     rx_queue_30_drops: 0
     rx_queue_30_xdp_redirect: 0
     rx_queue_30_xdp_drops: 0
     rx_queue_30_xdp_tx: 0
     rx_queue_30_xdp_tx_errors: 0
     rx_queue_31_xdp_packets: 0
     rx_queue_31_xdp_bytes: 0
     rx_queue_31_drops: 0
     rx_queue_31_xdp_redirect: 0
     rx_queue_31_xdp_drops: 0
     rx_queue_31_xdp_tx: 0
     rx_queue_31_xdp_tx_errors: 0
     rx_queue_32_xdp_packets: 0
     rx_queue_32_xdp_bytes: 0
     rx_queue_32_drops: 0
     rx_queue_32_xdp_redirect: 0
     rx_queue_32_xdp_drops: 0
     rx_queue_32_xdp_tx: 0
     rx_queue_32_xdp_tx_errors: 0
     rx_queue_33_xdp_packets: 0
     rx_queue_33_xdp_bytes: 0
     rx_queue_33_drops: 0
     rx_queue_33_xdp_redirect: 0
     rx_queue_33_xdp_drops: 0
     rx_queue_33_xdp_tx: 0
     rx_queue_33_xdp_tx_errors: 0
     rx_queue_34_xdp_packets: 0
     rx_queue_34_xdp_bytes: 0
     rx_queue_34_drops: 0
     rx_queue_34_xdp_redirect: 0
     rx_queue_34_xdp_drops: 0
     rx_queue_34_xdp_tx: 0
     rx_queue_34_xdp_tx_errors: 0
     rx_queue_35_xdp_packets: 0
     rx_queue_35_xdp_bytes: 0
     rx_queue_35_drops: 0
     rx_queue_35_xdp_redirect: 0
     rx_queue_35_xdp_drops: 0
     rx_queue_35_xdp_tx: 0
     rx_queue_35_xdp_tx_errors: 0
     rx_queue_36_xdp_packets: 0
     rx_queue_36_xdp_bytes: 0
     rx_queue_36_drops: 0
     rx_queue_36_xdp_redirect: 0
     rx_queue_36_xdp_drops: 0
     rx_queue_36_xdp_tx: 0
     rx_queue_36_xdp_tx_errors: 0
     rx_queue_37_xdp_packets: 0
     rx_queue_37_xdp_bytes: 0
     rx_queue_37_drops: 0
     rx_queue_37_xdp_redirect: 0
     rx_queue_37_xdp_drops: 0
     rx_queue_37_xdp_tx: 0
     rx_queue_37_xdp_tx_errors: 0
     rx_queue_38_xdp_packets: 2
     rx_queue_38_xdp_bytes: 112
     rx_queue_38_drops: 0
     rx_queue_38_xdp_redirect: 0
     rx_queue_38_xdp_drops: 0
     rx_queue_38_xdp_tx: 0
     rx_queue_38_xdp_tx_errors: 0
     rx_queue_39_xdp_packets: 0
     rx_queue_39_xdp_bytes: 0
     rx_queue_39_drops: 0
     rx_queue_39_xdp_redirect: 0
     rx_queue_39_xdp_drops: 0
     rx_queue_39_xdp_tx: 0
     rx_queue_39_xdp_tx_errors: 0
     rx_queue_40_xdp_packets: 0
     rx_queue_40_xdp_bytes: 0
     rx_queue_40_drops: 0
     rx_queue_40_xdp_redirect: 0
     rx_queue_40_xdp_drops: 0
     rx_queue_40_xdp_tx: 0
     rx_queue_40_xdp_tx_errors: 0
     rx_queue_41_xdp_packets: 0
     rx_queue_41_xdp_bytes: 0
     rx_queue_41_drops: 0
     rx_queue_41_xdp_redirect: 0
     rx_queue_41_xdp_drops: 0
     rx_queue_41_xdp_tx: 0
     rx_queue_41_xdp_tx_errors: 0
     rx_queue_42_xdp_packets: 0
     rx_queue_42_xdp_bytes: 0
     rx_queue_42_drops: 0
     rx_queue_42_xdp_redirect: 0
     rx_queue_42_xdp_drops: 0
     rx_queue_42_xdp_tx: 0
     rx_queue_42_xdp_tx_errors: 0
     rx_queue_43_xdp_packets: 0
     rx_queue_43_xdp_bytes: 0
     rx_queue_43_drops: 0
     rx_queue_43_xdp_redirect: 0
     rx_queue_43_xdp_drops: 0
     rx_queue_43_xdp_tx: 0
     rx_queue_43_xdp_tx_errors: 0
     rx_queue_44_xdp_packets: 0
     rx_queue_44_xdp_bytes: 0
     rx_queue_44_drops: 0
     rx_queue_44_xdp_redirect: 0
     rx_queue_44_xdp_drops: 0
     rx_queue_44_xdp_tx: 0
     rx_queue_44_xdp_tx_errors: 0
     rx_queue_45_xdp_packets: 0
     rx_queue_45_xdp_bytes: 0
     rx_queue_45_drops: 0
     rx_queue_45_xdp_redirect: 0
     rx_queue_45_xdp_drops: 0
     rx_queue_45_xdp_tx: 0
     rx_queue_45_xdp_tx_errors: 0
     rx_queue_46_xdp_packets: 0
     rx_queue_46_xdp_bytes: 0
     rx_queue_46_drops: 0
     rx_queue_46_xdp_redirect: 0
     rx_queue_46_xdp_drops: 0
     rx_queue_46_xdp_tx: 0
     rx_queue_46_xdp_tx_errors: 0
     rx_queue_47_xdp_packets: 0
     rx_queue_47_xdp_bytes: 0
     rx_queue_47_drops: 0
     rx_queue_47_xdp_redirect: 0
     rx_queue_47_xdp_drops: 0
     rx_queue_47_xdp_tx: 0
     rx_queue_47_xdp_tx_errors: 0
     rx_queue_48_xdp_packets: 0
     rx_queue_48_xdp_bytes: 0
     rx_queue_48_drops: 0
     rx_queue_48_xdp_redirect: 0
     rx_queue_48_xdp_drops: 0
     rx_queue_48_xdp_tx: 0
     rx_queue_48_xdp_tx_errors: 0
     rx_queue_49_xdp_packets: 0
     rx_queue_49_xdp_bytes: 0
     rx_queue_49_drops: 0
     rx_queue_49_xdp_redirect: 0
     rx_queue_49_xdp_drops: 0
     rx_queue_49_xdp_tx: 0
     rx_queue_49_xdp_tx_errors: 0
     rx_queue_50_xdp_packets: 0
     rx_queue_50_xdp_bytes: 0
     rx_queue_50_drops: 0
     rx_queue_50_xdp_redirect: 0
     rx_queue_50_xdp_drops: 0
     rx_queue_50_xdp_tx: 0
     rx_queue_50_xdp_tx_errors: 0
     rx_queue_51_xdp_packets: 0
     rx_queue_51_xdp_bytes: 0
     rx_queue_51_drops: 0
     rx_queue_51_xdp_redirect: 0
     rx_queue_51_xdp_drops: 0
     rx_queue_51_xdp_tx: 0
     rx_queue_51_xdp_tx_errors: 0
     rx_queue_52_xdp_packets: 0
     rx_queue_52_xdp_bytes: 0
     rx_queue_52_drops: 0
     rx_queue_52_xdp_redirect: 0
     rx_queue_52_xdp_drops: 0
     rx_queue_52_xdp_tx: 0
     rx_queue_52_xdp_tx_errors: 0
     rx_queue_53_xdp_packets: 0
     rx_queue_53_xdp_bytes: 0
     rx_queue_53_drops: 0
     rx_queue_53_xdp_redirect: 0
     rx_queue_53_xdp_drops: 0
     rx_queue_53_xdp_tx: 0
     rx_queue_53_xdp_tx_errors: 0
     rx_queue_54_xdp_packets: 0
     rx_queue_54_xdp_bytes: 0
     rx_queue_54_drops: 0
     rx_queue_54_xdp_redirect: 0
     rx_queue_54_xdp_drops: 0
     rx_queue_54_xdp_tx: 0
     rx_queue_54_xdp_tx_errors: 0
     rx_queue_55_xdp_packets: 0
     rx_queue_55_xdp_bytes: 0
     rx_queue_55_drops: 0
     rx_queue_55_xdp_redirect: 0
     rx_queue_55_xdp_drops: 0
     rx_queue_55_xdp_tx: 0
     rx_queue_55_xdp_tx_errors: 0
     rx_queue_56_xdp_packets: 0
     rx_queue_56_xdp_bytes: 0
     rx_queue_56_drops: 0
     rx_queue_56_xdp_redirect: 0
     rx_queue_56_xdp_drops: 0
     rx_queue_56_xdp_tx: 0
     rx_queue_56_xdp_tx_errors: 0
     rx_queue_57_xdp_packets: 0
     rx_queue_57_xdp_bytes: 0
     rx_queue_57_drops: 0
     rx_queue_57_xdp_redirect: 0
     rx_queue_57_xdp_drops: 0
     rx_queue_57_xdp_tx: 0
     rx_queue_57_xdp_tx_errors: 0
     rx_queue_58_xdp_packets: 0
     rx_queue_58_xdp_bytes: 0
     rx_queue_58_drops: 0
     rx_queue_58_xdp_redirect: 0
     rx_queue_58_xdp_drops: 0
     rx_queue_58_xdp_tx: 0
     rx_queue_58_xdp_tx_errors: 0
     rx_queue_59_xdp_packets: 0
     rx_queue_59_xdp_bytes: 0
     rx_queue_59_drops: 0
     rx_queue_59_xdp_redirect: 0
     rx_queue_59_xdp_drops: 0
     rx_queue_59_xdp_tx: 0
     rx_queue_59_xdp_tx_errors: 0
     rx_queue_60_xdp_packets: 0
     rx_queue_60_xdp_bytes: 0
     rx_queue_60_drops: 0
     rx_queue_60_xdp_redirect: 0
     rx_queue_60_xdp_drops: 0
     rx_queue_60_xdp_tx: 0
     rx_queue_60_xdp_tx_errors: 0
     rx_queue_61_xdp_packets: 0
     rx_queue_61_xdp_bytes: 0
     rx_queue_61_drops: 0
     rx_queue_61_xdp_redirect: 0
     rx_queue_61_xdp_drops: 0
     rx_queue_61_xdp_tx: 0
     rx_queue_61_xdp_tx_errors: 0
     rx_queue_62_xdp_packets: 0
     rx_queue_62_xdp_bytes: 0
     rx_queue_62_drops: 0
     rx_queue_62_xdp_redirect: 0
     rx_queue_62_xdp_drops: 0
     rx_queue_62_xdp_tx: 0
     rx_queue_62_xdp_tx_errors: 0
     rx_queue_63_xdp_packets: 0
     rx_queue_63_xdp_bytes: 0
     rx_queue_63_drops: 0
     rx_queue_63_xdp_redirect: 0
     rx_queue_63_xdp_drops: 0
     rx_queue_63_xdp_tx: 0
     rx_queue_63_xdp_tx_errors: 0
     tx_queue_0_xdp_xmit: 0
     tx_queue_0_xdp_xmit_errors: 0
"""
    data1_end = """NIC statistics:
     peer_ifindex: 2
     rx_queue_0_xdp_packets: 0
     rx_queue_0_xdp_bytes: 0
     rx_queue_0_drops: 0
     rx_queue_0_xdp_redirect: 0
     rx_queue_0_xdp_drops: 0
     rx_queue_0_xdp_tx: 0
     rx_queue_0_xdp_tx_errors: 0
     rx_queue_1_xdp_packets: 0
     rx_queue_1_xdp_bytes: 0
     rx_queue_1_drops: 0
     rx_queue_1_xdp_redirect: 0
     rx_queue_1_xdp_drops: 0
     rx_queue_1_xdp_tx: 0
     rx_queue_1_xdp_tx_errors: 0
     rx_queue_2_xdp_packets: 0
     rx_queue_2_xdp_bytes: 0
     rx_queue_2_drops: 0
     rx_queue_2_xdp_redirect: 0
     rx_queue_2_xdp_drops: 0
     rx_queue_2_xdp_tx: 0
     rx_queue_2_xdp_tx_errors: 0
     rx_queue_3_xdp_packets: 0
     rx_queue_3_xdp_bytes: 0
     rx_queue_3_drops: 0
     rx_queue_3_xdp_redirect: 0
     rx_queue_3_xdp_drops: 0
     rx_queue_3_xdp_tx: 0
     rx_queue_3_xdp_tx_errors: 0
     rx_queue_4_xdp_packets: 0
     rx_queue_4_xdp_bytes: 0
     rx_queue_4_drops: 0
     rx_queue_4_xdp_redirect: 0
     rx_queue_4_xdp_drops: 0
     rx_queue_4_xdp_tx: 0
     rx_queue_4_xdp_tx_errors: 0
     rx_queue_5_xdp_packets: 0
     rx_queue_5_xdp_bytes: 0
     rx_queue_5_drops: 0
     rx_queue_5_xdp_redirect: 0
     rx_queue_5_xdp_drops: 0
     rx_queue_5_xdp_tx: 0
     rx_queue_5_xdp_tx_errors: 0
     rx_queue_6_xdp_packets: 0
     rx_queue_6_xdp_bytes: 0
     rx_queue_6_drops: 0
     rx_queue_6_xdp_redirect: 0
     rx_queue_6_xdp_drops: 0
     rx_queue_6_xdp_tx: 0
     rx_queue_6_xdp_tx_errors: 0
     rx_queue_7_xdp_packets: 0
     rx_queue_7_xdp_bytes: 0
     rx_queue_7_drops: 0
     rx_queue_7_xdp_redirect: 0
     rx_queue_7_xdp_drops: 0
     rx_queue_7_xdp_tx: 0
     rx_queue_7_xdp_tx_errors: 0
     rx_queue_8_xdp_packets: 0
     rx_queue_8_xdp_bytes: 0
     rx_queue_8_drops: 0
     rx_queue_8_xdp_redirect: 0
     rx_queue_8_xdp_drops: 0
     rx_queue_8_xdp_tx: 0
     rx_queue_8_xdp_tx_errors: 0
     rx_queue_9_xdp_packets: 0
     rx_queue_9_xdp_bytes: 0
     rx_queue_9_drops: 0
     rx_queue_9_xdp_redirect: 0
     rx_queue_9_xdp_drops: 0
     rx_queue_9_xdp_tx: 0
     rx_queue_9_xdp_tx_errors: 0
     rx_queue_10_xdp_packets: 0
     rx_queue_10_xdp_bytes: 0
     rx_queue_10_drops: 0
     rx_queue_10_xdp_redirect: 0
     rx_queue_10_xdp_drops: 0
     rx_queue_10_xdp_tx: 0
     rx_queue_10_xdp_tx_errors: 0
     rx_queue_11_xdp_packets: 2
     rx_queue_11_xdp_bytes: 152
     rx_queue_11_drops: 0
     rx_queue_11_xdp_redirect: 0
     rx_queue_11_xdp_drops: 0
     rx_queue_11_xdp_tx: 0
     rx_queue_11_xdp_tx_errors: 0
     rx_queue_12_xdp_packets: 1
     rx_queue_12_xdp_bytes: 72
     rx_queue_12_drops: 0
     rx_queue_12_xdp_redirect: 0
     rx_queue_12_xdp_drops: 0
     rx_queue_12_xdp_tx: 0
     rx_queue_12_xdp_tx_errors: 0
     rx_queue_13_xdp_packets: 0
     rx_queue_13_xdp_bytes: 0
     rx_queue_13_drops: 0
     rx_queue_13_xdp_redirect: 0
     rx_queue_13_xdp_drops: 0
     rx_queue_13_xdp_tx: 0
     rx_queue_13_xdp_tx_errors: 0
     rx_queue_14_xdp_packets: 0
     rx_queue_14_xdp_bytes: 0
     rx_queue_14_drops: 0
     rx_queue_14_xdp_redirect: 0
     rx_queue_14_xdp_drops: 0
     rx_queue_14_xdp_tx: 0
     rx_queue_14_xdp_tx_errors: 0
     rx_queue_15_xdp_packets: 0
     rx_queue_15_xdp_bytes: 0
     rx_queue_15_drops: 0
     rx_queue_15_xdp_redirect: 0
     rx_queue_15_xdp_drops: 0
     rx_queue_15_xdp_tx: 0
     rx_queue_15_xdp_tx_errors: 0
     rx_queue_16_xdp_packets: 0
     rx_queue_16_xdp_bytes: 0
     rx_queue_16_drops: 0
     rx_queue_16_xdp_redirect: 0
     rx_queue_16_xdp_drops: 0
     rx_queue_16_xdp_tx: 0
     rx_queue_16_xdp_tx_errors: 0
     rx_queue_17_xdp_packets: 0
     rx_queue_17_xdp_bytes: 0
     rx_queue_17_drops: 0
     rx_queue_17_xdp_redirect: 0
     rx_queue_17_xdp_drops: 0
     rx_queue_17_xdp_tx: 0
     rx_queue_17_xdp_tx_errors: 0
     rx_queue_18_xdp_packets: 0
     rx_queue_18_xdp_bytes: 0
     rx_queue_18_drops: 0
     rx_queue_18_xdp_redirect: 0
     rx_queue_18_xdp_drops: 0
     rx_queue_18_xdp_tx: 0
     rx_queue_18_xdp_tx_errors: 0
     rx_queue_19_xdp_packets: 0
     rx_queue_19_xdp_bytes: 0
     rx_queue_19_drops: 0
     rx_queue_19_xdp_redirect: 0
     rx_queue_19_xdp_drops: 0
     rx_queue_19_xdp_tx: 0
     rx_queue_19_xdp_tx_errors: 0
     rx_queue_20_xdp_packets: 0
     rx_queue_20_xdp_bytes: 0
     rx_queue_20_drops: 0
     rx_queue_20_xdp_redirect: 0
     rx_queue_20_xdp_drops: 0
     rx_queue_20_xdp_tx: 0
     rx_queue_20_xdp_tx_errors: 0
     rx_queue_21_xdp_packets: 2
     rx_queue_21_xdp_bytes: 152
     rx_queue_21_drops: 0
     rx_queue_21_xdp_redirect: 0
     rx_queue_21_xdp_drops: 0
     rx_queue_21_xdp_tx: 0
     rx_queue_21_xdp_tx_errors: 0
     rx_queue_22_xdp_packets: 0
     rx_queue_22_xdp_bytes: 0
     rx_queue_22_drops: 0
     rx_queue_22_xdp_redirect: 0
     rx_queue_22_xdp_drops: 0
     rx_queue_22_xdp_tx: 0
     rx_queue_22_xdp_tx_errors: 0
     rx_queue_23_xdp_packets: 0
     rx_queue_23_xdp_bytes: 0
     rx_queue_23_drops: 0
     rx_queue_23_xdp_redirect: 0
     rx_queue_23_xdp_drops: 0
     rx_queue_23_xdp_tx: 0
     rx_queue_23_xdp_tx_errors: 0
     rx_queue_24_xdp_packets: 0
     rx_queue_24_xdp_bytes: 0
     rx_queue_24_drops: 0
     rx_queue_24_xdp_redirect: 0
     rx_queue_24_xdp_drops: 0
     rx_queue_24_xdp_tx: 0
     rx_queue_24_xdp_tx_errors: 0
     rx_queue_25_xdp_packets: 0
     rx_queue_25_xdp_bytes: 0
     rx_queue_25_drops: 0
     rx_queue_25_xdp_redirect: 0
     rx_queue_25_xdp_drops: 0
     rx_queue_25_xdp_tx: 0
     rx_queue_25_xdp_tx_errors: 0
     rx_queue_26_xdp_packets: 0
     rx_queue_26_xdp_bytes: 0
     rx_queue_26_drops: 0
     rx_queue_26_xdp_redirect: 0
     rx_queue_26_xdp_drops: 0
     rx_queue_26_xdp_tx: 0
     rx_queue_26_xdp_tx_errors: 0
     rx_queue_27_xdp_packets: 0
     rx_queue_27_xdp_bytes: 0
     rx_queue_27_drops: 0
     rx_queue_27_xdp_redirect: 0
     rx_queue_27_xdp_drops: 0
     rx_queue_27_xdp_tx: 0
     rx_queue_27_xdp_tx_errors: 0
     rx_queue_28_xdp_packets: 0
     rx_queue_28_xdp_bytes: 0
     rx_queue_28_drops: 0
     rx_queue_28_xdp_redirect: 0
     rx_queue_28_xdp_drops: 0
     rx_queue_28_xdp_tx: 0
     rx_queue_28_xdp_tx_errors: 0
     rx_queue_29_xdp_packets: 0
     rx_queue_29_xdp_bytes: 0
     rx_queue_29_drops: 0
     rx_queue_29_xdp_redirect: 0
     rx_queue_29_xdp_drops: 0
     rx_queue_29_xdp_tx: 0
     rx_queue_29_xdp_tx_errors: 0
     rx_queue_30_xdp_packets: 0
     rx_queue_30_xdp_bytes: 0
     rx_queue_30_drops: 0
     rx_queue_30_xdp_redirect: 0
     rx_queue_30_xdp_drops: 0
     rx_queue_30_xdp_tx: 0
     rx_queue_30_xdp_tx_errors: 0
     rx_queue_31_xdp_packets: 0
     rx_queue_31_xdp_bytes: 0
     rx_queue_31_drops: 0
     rx_queue_31_xdp_redirect: 0
     rx_queue_31_xdp_drops: 0
     rx_queue_31_xdp_tx: 0
     rx_queue_31_xdp_tx_errors: 0
     rx_queue_32_xdp_packets: 0
     rx_queue_32_xdp_bytes: 0
     rx_queue_32_drops: 0
     rx_queue_32_xdp_redirect: 0
     rx_queue_32_xdp_drops: 0
     rx_queue_32_xdp_tx: 0
     rx_queue_32_xdp_tx_errors: 0
     rx_queue_33_xdp_packets: 0
     rx_queue_33_xdp_bytes: 0
     rx_queue_33_drops: 0
     rx_queue_33_xdp_redirect: 0
     rx_queue_33_xdp_drops: 0
     rx_queue_33_xdp_tx: 0
     rx_queue_33_xdp_tx_errors: 0
     rx_queue_34_xdp_packets: 0
     rx_queue_34_xdp_bytes: 0
     rx_queue_34_drops: 0
     rx_queue_34_xdp_redirect: 0
     rx_queue_34_xdp_drops: 0
     rx_queue_34_xdp_tx: 0
     rx_queue_34_xdp_tx_errors: 0
     rx_queue_35_xdp_packets: 0
     rx_queue_35_xdp_bytes: 0
     rx_queue_35_drops: 0
     rx_queue_35_xdp_redirect: 0
     rx_queue_35_xdp_drops: 0
     rx_queue_35_xdp_tx: 0
     rx_queue_35_xdp_tx_errors: 0
     rx_queue_36_xdp_packets: 0
     rx_queue_36_xdp_bytes: 0
     rx_queue_36_drops: 0
     rx_queue_36_xdp_redirect: 0
     rx_queue_36_xdp_drops: 0
     rx_queue_36_xdp_tx: 0
     rx_queue_36_xdp_tx_errors: 0
     rx_queue_37_xdp_packets: 0
     rx_queue_37_xdp_bytes: 0
     rx_queue_37_drops: 0
     rx_queue_37_xdp_redirect: 0
     rx_queue_37_xdp_drops: 0
     rx_queue_37_xdp_tx: 0
     rx_queue_37_xdp_tx_errors: 0
     rx_queue_38_xdp_packets: 2
     rx_queue_38_xdp_bytes: 112
     rx_queue_38_drops: 0
     rx_queue_38_xdp_redirect: 0
     rx_queue_38_xdp_drops: 0
     rx_queue_38_xdp_tx: 0
     rx_queue_38_xdp_tx_errors: 0
     rx_queue_39_xdp_packets: 0
     rx_queue_39_xdp_bytes: 0
     rx_queue_39_drops: 0
     rx_queue_39_xdp_redirect: 0
     rx_queue_39_xdp_drops: 0
     rx_queue_39_xdp_tx: 0
     rx_queue_39_xdp_tx_errors: 0
     rx_queue_40_xdp_packets: 0
     rx_queue_40_xdp_bytes: 0
     rx_queue_40_drops: 0
     rx_queue_40_xdp_redirect: 0
     rx_queue_40_xdp_drops: 0
     rx_queue_40_xdp_tx: 0
     rx_queue_40_xdp_tx_errors: 0
     rx_queue_41_xdp_packets: 0
     rx_queue_41_xdp_bytes: 0
     rx_queue_41_drops: 0
     rx_queue_41_xdp_redirect: 0
     rx_queue_41_xdp_drops: 0
     rx_queue_41_xdp_tx: 0
     rx_queue_41_xdp_tx_errors: 0
     rx_queue_42_xdp_packets: 0
     rx_queue_42_xdp_bytes: 0
     rx_queue_42_drops: 0
     rx_queue_42_xdp_redirect: 0
     rx_queue_42_xdp_drops: 0
     rx_queue_42_xdp_tx: 0
     rx_queue_42_xdp_tx_errors: 0
     rx_queue_43_xdp_packets: 0
     rx_queue_43_xdp_bytes: 0
     rx_queue_43_drops: 0
     rx_queue_43_xdp_redirect: 0
     rx_queue_43_xdp_drops: 0
     rx_queue_43_xdp_tx: 0
     rx_queue_43_xdp_tx_errors: 0
     rx_queue_44_xdp_packets: 0
     rx_queue_44_xdp_bytes: 0
     rx_queue_44_drops: 0
     rx_queue_44_xdp_redirect: 0
     rx_queue_44_xdp_drops: 0
     rx_queue_44_xdp_tx: 0
     rx_queue_44_xdp_tx_errors: 0
     rx_queue_45_xdp_packets: 0
     rx_queue_45_xdp_bytes: 0
     rx_queue_45_drops: 0
     rx_queue_45_xdp_redirect: 0
     rx_queue_45_xdp_drops: 0
     rx_queue_45_xdp_tx: 0
     rx_queue_45_xdp_tx_errors: 0
     rx_queue_46_xdp_packets: 0
     rx_queue_46_xdp_bytes: 0
     rx_queue_46_drops: 0
     rx_queue_46_xdp_redirect: 0
     rx_queue_46_xdp_drops: 0
     rx_queue_46_xdp_tx: 0
     rx_queue_46_xdp_tx_errors: 0
     rx_queue_47_xdp_packets: 0
     rx_queue_47_xdp_bytes: 0
     rx_queue_47_drops: 0
     rx_queue_47_xdp_redirect: 0
     rx_queue_47_xdp_drops: 0
     rx_queue_47_xdp_tx: 0
     rx_queue_47_xdp_tx_errors: 0
     rx_queue_48_xdp_packets: 0
     rx_queue_48_xdp_bytes: 0
     rx_queue_48_drops: 0
     rx_queue_48_xdp_redirect: 0
     rx_queue_48_xdp_drops: 0
     rx_queue_48_xdp_tx: 0
     rx_queue_48_xdp_tx_errors: 0
     rx_queue_49_xdp_packets: 0
     rx_queue_49_xdp_bytes: 0
     rx_queue_49_drops: 0
     rx_queue_49_xdp_redirect: 0
     rx_queue_49_xdp_drops: 0
     rx_queue_49_xdp_tx: 0
     rx_queue_49_xdp_tx_errors: 0
     rx_queue_50_xdp_packets: 0
     rx_queue_50_xdp_bytes: 0
     rx_queue_50_drops: 0
     rx_queue_50_xdp_redirect: 0
     rx_queue_50_xdp_drops: 0
     rx_queue_50_xdp_tx: 0
     rx_queue_50_xdp_tx_errors: 0
     rx_queue_51_xdp_packets: 0
     rx_queue_51_xdp_bytes: 0
     rx_queue_51_drops: 0
     rx_queue_51_xdp_redirect: 0
     rx_queue_51_xdp_drops: 0
     rx_queue_51_xdp_tx: 0
     rx_queue_51_xdp_tx_errors: 0
     rx_queue_52_xdp_packets: 0
     rx_queue_52_xdp_bytes: 0
     rx_queue_52_drops: 0
     rx_queue_52_xdp_redirect: 0
     rx_queue_52_xdp_drops: 0
     rx_queue_52_xdp_tx: 0
     rx_queue_52_xdp_tx_errors: 0
     rx_queue_53_xdp_packets: 0
     rx_queue_53_xdp_bytes: 0
     rx_queue_53_drops: 0
     rx_queue_53_xdp_redirect: 0
     rx_queue_53_xdp_drops: 0
     rx_queue_53_xdp_tx: 0
     rx_queue_53_xdp_tx_errors: 0
     rx_queue_54_xdp_packets: 0
     rx_queue_54_xdp_bytes: 0
     rx_queue_54_drops: 0
     rx_queue_54_xdp_redirect: 0
     rx_queue_54_xdp_drops: 0
     rx_queue_54_xdp_tx: 0
     rx_queue_54_xdp_tx_errors: 0
     rx_queue_55_xdp_packets: 0
     rx_queue_55_xdp_bytes: 0
     rx_queue_55_drops: 0
     rx_queue_55_xdp_redirect: 0
     rx_queue_55_xdp_drops: 0
     rx_queue_55_xdp_tx: 0
     rx_queue_55_xdp_tx_errors: 0
     rx_queue_56_xdp_packets: 0
     rx_queue_56_xdp_bytes: 0
     rx_queue_56_drops: 0
     rx_queue_56_xdp_redirect: 0
     rx_queue_56_xdp_drops: 0
     rx_queue_56_xdp_tx: 0
     rx_queue_56_xdp_tx_errors: 0
     rx_queue_57_xdp_packets: 0
     rx_queue_57_xdp_bytes: 0
     rx_queue_57_drops: 0
     rx_queue_57_xdp_redirect: 0
     rx_queue_57_xdp_drops: 0
     rx_queue_57_xdp_tx: 0
     rx_queue_57_xdp_tx_errors: 0
     rx_queue_58_xdp_packets: 0
     rx_queue_58_xdp_bytes: 0
     rx_queue_58_drops: 0
     rx_queue_58_xdp_redirect: 0
     rx_queue_58_xdp_drops: 0
     rx_queue_58_xdp_tx: 0
     rx_queue_58_xdp_tx_errors: 0
     rx_queue_59_xdp_packets: 0
     rx_queue_59_xdp_bytes: 0
     rx_queue_59_drops: 0
     rx_queue_59_xdp_redirect: 0
     rx_queue_59_xdp_drops: 0
     rx_queue_59_xdp_tx: 0
     rx_queue_59_xdp_tx_errors: 0
     rx_queue_60_xdp_packets: 0
     rx_queue_60_xdp_bytes: 0
     rx_queue_60_drops: 0
     rx_queue_60_xdp_redirect: 0
     rx_queue_60_xdp_drops: 0
     rx_queue_60_xdp_tx: 0
     rx_queue_60_xdp_tx_errors: 0
     rx_queue_61_xdp_packets: 0
     rx_queue_61_xdp_bytes: 0
     rx_queue_61_drops: 0
     rx_queue_61_xdp_redirect: 0
     rx_queue_61_xdp_drops: 0
     rx_queue_61_xdp_tx: 0
     rx_queue_61_xdp_tx_errors: 0
     rx_queue_62_xdp_packets: 0
     rx_queue_62_xdp_bytes: 0
     rx_queue_62_drops: 0
     rx_queue_62_xdp_redirect: 0
     rx_queue_62_xdp_drops: 0
     rx_queue_62_xdp_tx: 0
     rx_queue_62_xdp_tx_errors: 0
     rx_queue_63_xdp_packets: 0
     rx_queue_63_xdp_bytes: 0
     rx_queue_63_drops: 0
     rx_queue_63_xdp_redirect: 0
     rx_queue_63_xdp_drops: 0
     rx_queue_63_xdp_tx: 0
     rx_queue_63_xdp_tx_errors: 0
     tx_queue_0_xdp_xmit: 0
     tx_queue_0_xdp_xmit_errors: 0
"""
    data2_end = """NIC statistics:
     peer_ifindex: 2
     rx_queue_0_xdp_packets: 0
     rx_queue_0_xdp_bytes: 0
     rx_queue_0_drops: 0
     rx_queue_0_xdp_redirect: 0
     rx_queue_0_xdp_drops: 0
     rx_queue_0_xdp_tx: 0
     rx_queue_0_xdp_tx_errors: 0
     rx_queue_1_xdp_packets: 0
     rx_queue_1_xdp_bytes: 0
     rx_queue_1_drops: 0
     rx_queue_1_xdp_redirect: 0
     rx_queue_1_xdp_drops: 0
     rx_queue_1_xdp_tx: 0
     rx_queue_1_xdp_tx_errors: 0
     rx_queue_2_xdp_packets: 0
     rx_queue_2_xdp_bytes: 0
     rx_queue_2_drops: 0
     rx_queue_2_xdp_redirect: 0
     rx_queue_2_xdp_drops: 0
     rx_queue_2_xdp_tx: 0
     rx_queue_2_xdp_tx_errors: 0
     rx_queue_3_xdp_packets: 0
     rx_queue_3_xdp_bytes: 0
     rx_queue_3_drops: 0
     rx_queue_3_xdp_redirect: 0
     rx_queue_3_xdp_drops: 0
     rx_queue_3_xdp_tx: 0
     rx_queue_3_xdp_tx_errors: 0
     rx_queue_4_xdp_packets: 0
     rx_queue_4_xdp_bytes: 0
     rx_queue_4_drops: 0
     rx_queue_4_xdp_redirect: 0
     rx_queue_4_xdp_drops: 0
     rx_queue_4_xdp_tx: 0
     rx_queue_4_xdp_tx_errors: 0
     rx_queue_5_xdp_packets: 0
     rx_queue_5_xdp_bytes: 0
     rx_queue_5_drops: 0
     rx_queue_5_xdp_redirect: 0
     rx_queue_5_xdp_drops: 0
     rx_queue_5_xdp_tx: 0
     rx_queue_5_xdp_tx_errors: 0
     rx_queue_6_xdp_packets: 0
     rx_queue_6_xdp_bytes: 0
     rx_queue_6_drops: 0
     rx_queue_6_xdp_redirect: 0
     rx_queue_6_xdp_drops: 0
     rx_queue_6_xdp_tx: 0
     rx_queue_6_xdp_tx_errors: 0
     rx_queue_7_xdp_packets: 0
     rx_queue_7_xdp_bytes: 0
     rx_queue_7_drops: 0
     rx_queue_7_xdp_redirect: 0
     rx_queue_7_xdp_drops: 0
     rx_queue_7_xdp_tx: 0
     rx_queue_7_xdp_tx_errors: 0
     rx_queue_8_xdp_packets: 0
     rx_queue_8_xdp_bytes: 0
     rx_queue_8_drops: 0
     rx_queue_8_xdp_redirect: 0
     rx_queue_8_xdp_drops: 0
     rx_queue_8_xdp_tx: 0
     rx_queue_8_xdp_tx_errors: 0
     rx_queue_9_xdp_packets: 0
     rx_queue_9_xdp_bytes: 0
     rx_queue_9_drops: 0
     rx_queue_9_xdp_redirect: 0
     rx_queue_9_xdp_drops: 0
     rx_queue_9_xdp_tx: 0
     rx_queue_9_xdp_tx_errors: 0
     rx_queue_10_xdp_packets: 0
     rx_queue_10_xdp_bytes: 0
     rx_queue_10_drops: 0
     rx_queue_10_xdp_redirect: 0
     rx_queue_10_xdp_drops: 0
     rx_queue_10_xdp_tx: 0
     rx_queue_10_xdp_tx_errors: 0
     rx_queue_11_xdp_packets: 2
     rx_queue_11_xdp_bytes: 152
     rx_queue_11_drops: 0
     rx_queue_11_xdp_redirect: 0
     rx_queue_11_xdp_drops: 0
     rx_queue_11_xdp_tx: 0
     rx_queue_11_xdp_tx_errors: 0
     rx_queue_12_xdp_packets: 1
     rx_queue_12_xdp_bytes: 72
     rx_queue_12_drops: 0
     rx_queue_12_xdp_redirect: 0
     rx_queue_12_xdp_drops: 0
     rx_queue_12_xdp_tx: 0
     rx_queue_12_xdp_tx_errors: 0
     rx_queue_13_xdp_packets: 0
     rx_queue_13_xdp_bytes: 0
     rx_queue_13_drops: 0
     rx_queue_13_xdp_redirect: 0
     rx_queue_13_xdp_drops: 0
     rx_queue_13_xdp_tx: 0
     rx_queue_13_xdp_tx_errors: 0
     rx_queue_14_xdp_packets: 0
     rx_queue_14_xdp_bytes: 0
     rx_queue_14_drops: 0
     rx_queue_14_xdp_redirect: 0
     rx_queue_14_xdp_drops: 0
     rx_queue_14_xdp_tx: 0
     rx_queue_14_xdp_tx_errors: 0
     rx_queue_15_xdp_packets: 0
     rx_queue_15_xdp_bytes: 0
     rx_queue_15_drops: 0
     rx_queue_15_xdp_redirect: 0
     rx_queue_15_xdp_drops: 0
     rx_queue_15_xdp_tx: 0
     rx_queue_15_xdp_tx_errors: 0
     rx_queue_16_xdp_packets: 0
     rx_queue_16_xdp_bytes: 0
     rx_queue_16_drops: 0
     rx_queue_16_xdp_redirect: 0
     rx_queue_16_xdp_drops: 0
     rx_queue_16_xdp_tx: 0
     rx_queue_16_xdp_tx_errors: 0
     rx_queue_17_xdp_packets: 0
     rx_queue_17_xdp_bytes: 0
     rx_queue_17_drops: 0
     rx_queue_17_xdp_redirect: 0
     rx_queue_17_xdp_drops: 0
     rx_queue_17_xdp_tx: 0
     rx_queue_17_xdp_tx_errors: 0
     rx_queue_18_xdp_packets: 0
     rx_queue_18_xdp_bytes: 0
     rx_queue_18_drops: 0
     rx_queue_18_xdp_redirect: 0
     rx_queue_18_xdp_drops: 0
     rx_queue_18_xdp_tx: 0
     rx_queue_18_xdp_tx_errors: 0
     rx_queue_19_xdp_packets: 0
     rx_queue_19_xdp_bytes: 0
     rx_queue_19_drops: 0
     rx_queue_19_xdp_redirect: 0
     rx_queue_19_xdp_drops: 0
     rx_queue_19_xdp_tx: 0
     rx_queue_19_xdp_tx_errors: 0
     rx_queue_20_xdp_packets: 0
     rx_queue_20_xdp_bytes: 0
     rx_queue_20_drops: 0
     rx_queue_20_xdp_redirect: 0
     rx_queue_20_xdp_drops: 0
     rx_queue_20_xdp_tx: 0
     rx_queue_20_xdp_tx_errors: 0
     rx_queue_21_xdp_packets: 2
     rx_queue_21_xdp_bytes: 152
     rx_queue_21_drops: 0
     rx_queue_21_xdp_redirect: 0
     rx_queue_21_xdp_drops: 0
     rx_queue_21_xdp_tx: 0
     rx_queue_21_xdp_tx_errors: 0
     rx_queue_22_xdp_packets: 0
     rx_queue_22_xdp_bytes: 0
     rx_queue_22_drops: 0
     rx_queue_22_xdp_redirect: 0
     rx_queue_22_xdp_drops: 0
     rx_queue_22_xdp_tx: 0
     rx_queue_22_xdp_tx_errors: 0
     rx_queue_23_xdp_packets: 0
     rx_queue_23_xdp_bytes: 0
     rx_queue_23_drops: 0
     rx_queue_23_xdp_redirect: 0
     rx_queue_23_xdp_drops: 0
     rx_queue_23_xdp_tx: 0
     rx_queue_23_xdp_tx_errors: 0
     rx_queue_24_xdp_packets: 0
     rx_queue_24_xdp_bytes: 0
     rx_queue_24_drops: 0
     rx_queue_24_xdp_redirect: 0
     rx_queue_24_xdp_drops: 0
     rx_queue_24_xdp_tx: 0
     rx_queue_24_xdp_tx_errors: 0
     rx_queue_25_xdp_packets: 0
     rx_queue_25_xdp_bytes: 0
     rx_queue_25_drops: 0
     rx_queue_25_xdp_redirect: 0
     rx_queue_25_xdp_drops: 0
     rx_queue_25_xdp_tx: 0
     rx_queue_25_xdp_tx_errors: 0
     rx_queue_26_xdp_packets: 0
     rx_queue_26_xdp_bytes: 0
     rx_queue_26_drops: 0
     rx_queue_26_xdp_redirect: 0
     rx_queue_26_xdp_drops: 0
     rx_queue_26_xdp_tx: 0
     rx_queue_26_xdp_tx_errors: 0
     rx_queue_27_xdp_packets: 0
     rx_queue_27_xdp_bytes: 0
     rx_queue_27_drops: 0
     rx_queue_27_xdp_redirect: 0
     rx_queue_27_xdp_drops: 0
     rx_queue_27_xdp_tx: 0
     rx_queue_27_xdp_tx_errors: 0
     rx_queue_28_xdp_packets: 0
     rx_queue_28_xdp_bytes: 0
     rx_queue_28_drops: 0
     rx_queue_28_xdp_redirect: 0
     rx_queue_28_xdp_drops: 0
     rx_queue_28_xdp_tx: 0
     rx_queue_28_xdp_tx_errors: 0
     rx_queue_29_xdp_packets: 0
     rx_queue_29_xdp_bytes: 0
     rx_queue_29_drops: 0
     rx_queue_29_xdp_redirect: 0
     rx_queue_29_xdp_drops: 0
     rx_queue_29_xdp_tx: 0
     rx_queue_29_xdp_tx_errors: 0
     rx_queue_30_xdp_packets: 0
     rx_queue_30_xdp_bytes: 0
     rx_queue_30_drops: 0
     rx_queue_30_xdp_redirect: 0
     rx_queue_30_xdp_drops: 0
     rx_queue_30_xdp_tx: 0
     rx_queue_30_xdp_tx_errors: 0
     rx_queue_31_xdp_packets: 0
     rx_queue_31_xdp_bytes: 0
     rx_queue_31_drops: 0
     rx_queue_31_xdp_redirect: 0
     rx_queue_31_xdp_drops: 0
     rx_queue_31_xdp_tx: 0
     rx_queue_31_xdp_tx_errors: 0
     rx_queue_32_xdp_packets: 0
     rx_queue_32_xdp_bytes: 0
     rx_queue_32_drops: 0
     rx_queue_32_xdp_redirect: 0
     rx_queue_32_xdp_drops: 0
     rx_queue_32_xdp_tx: 0
     rx_queue_32_xdp_tx_errors: 0
     rx_queue_33_xdp_packets: 0
     rx_queue_33_xdp_bytes: 0
     rx_queue_33_drops: 0
     rx_queue_33_xdp_redirect: 0
     rx_queue_33_xdp_drops: 0
     rx_queue_33_xdp_tx: 0
     rx_queue_33_xdp_tx_errors: 0
     rx_queue_34_xdp_packets: 0
     rx_queue_34_xdp_bytes: 0
     rx_queue_34_drops: 0
     rx_queue_34_xdp_redirect: 0
     rx_queue_34_xdp_drops: 0
     rx_queue_34_xdp_tx: 0
     rx_queue_34_xdp_tx_errors: 0
     rx_queue_35_xdp_packets: 0
     rx_queue_35_xdp_bytes: 0
     rx_queue_35_drops: 0
     rx_queue_35_xdp_redirect: 0
     rx_queue_35_xdp_drops: 0
     rx_queue_35_xdp_tx: 0
     rx_queue_35_xdp_tx_errors: 0
     rx_queue_36_xdp_packets: 0
     rx_queue_36_xdp_bytes: 0
     rx_queue_36_drops: 0
     rx_queue_36_xdp_redirect: 0
     rx_queue_36_xdp_drops: 0
     rx_queue_36_xdp_tx: 0
     rx_queue_36_xdp_tx_errors: 0
     rx_queue_37_xdp_packets: 0
     rx_queue_37_xdp_bytes: 0
     rx_queue_37_drops: 0
     rx_queue_37_xdp_redirect: 0
     rx_queue_37_xdp_drops: 0
     rx_queue_37_xdp_tx: 0
     rx_queue_37_xdp_tx_errors: 0
     rx_queue_38_xdp_packets: 2
     rx_queue_38_xdp_bytes: 112
     rx_queue_38_drops: 0
     rx_queue_38_xdp_redirect: 0
     rx_queue_38_xdp_drops: 0
     rx_queue_38_xdp_tx: 0
     rx_queue_38_xdp_tx_errors: 0
     rx_queue_39_xdp_packets: 0
     rx_queue_39_xdp_bytes: 0
     rx_queue_39_drops: 0
     rx_queue_39_xdp_redirect: 0
     rx_queue_39_xdp_drops: 0
     rx_queue_39_xdp_tx: 0
     rx_queue_39_xdp_tx_errors: 0
     rx_queue_40_xdp_packets: 0
     rx_queue_40_xdp_bytes: 0
     rx_queue_40_drops: 0
     rx_queue_40_xdp_redirect: 0
     rx_queue_40_xdp_drops: 0
     rx_queue_40_xdp_tx: 0
     rx_queue_40_xdp_tx_errors: 0
     rx_queue_41_xdp_packets: 0
     rx_queue_41_xdp_bytes: 0
     rx_queue_41_drops: 0
     rx_queue_41_xdp_redirect: 0
     rx_queue_41_xdp_drops: 0
     rx_queue_41_xdp_tx: 0
     rx_queue_41_xdp_tx_errors: 0
     rx_queue_42_xdp_packets: 0
     rx_queue_42_xdp_bytes: 0
     rx_queue_42_drops: 0
     rx_queue_42_xdp_redirect: 0
     rx_queue_42_xdp_drops: 0
     rx_queue_42_xdp_tx: 0
     rx_queue_42_xdp_tx_errors: 0
     rx_queue_43_xdp_packets: 0
     rx_queue_43_xdp_bytes: 0
     rx_queue_43_drops: 0
     rx_queue_43_xdp_redirect: 0
     rx_queue_43_xdp_drops: 0
     rx_queue_43_xdp_tx: 0
     rx_queue_43_xdp_tx_errors: 0
     rx_queue_44_xdp_packets: 0
     rx_queue_44_xdp_bytes: 0
     rx_queue_44_drops: 0
     rx_queue_44_xdp_redirect: 0
     rx_queue_44_xdp_drops: 0
     rx_queue_44_xdp_tx: 0
     rx_queue_44_xdp_tx_errors: 0
     rx_queue_45_xdp_packets: 0
     rx_queue_45_xdp_bytes: 0
     rx_queue_45_drops: 0
     rx_queue_45_xdp_redirect: 0
     rx_queue_45_xdp_drops: 0
     rx_queue_45_xdp_tx: 0
     rx_queue_45_xdp_tx_errors: 0
     rx_queue_46_xdp_packets: 0
     rx_queue_46_xdp_bytes: 0
     rx_queue_46_drops: 0
     rx_queue_46_xdp_redirect: 0
     rx_queue_46_xdp_drops: 0
     rx_queue_46_xdp_tx: 0
     rx_queue_46_xdp_tx_errors: 0
     rx_queue_47_xdp_packets: 0
     rx_queue_47_xdp_bytes: 0
     rx_queue_47_drops: 0
     rx_queue_47_xdp_redirect: 0
     rx_queue_47_xdp_drops: 0
     rx_queue_47_xdp_tx: 0
     rx_queue_47_xdp_tx_errors: 0
     rx_queue_48_xdp_packets: 0
     rx_queue_48_xdp_bytes: 0
     rx_queue_48_drops: 0
     rx_queue_48_xdp_redirect: 0
     rx_queue_48_xdp_drops: 0
     rx_queue_48_xdp_tx: 0
     rx_queue_48_xdp_tx_errors: 0
     rx_queue_49_xdp_packets: 0
     rx_queue_49_xdp_bytes: 0
     rx_queue_49_drops: 0
     rx_queue_49_xdp_redirect: 0
     rx_queue_49_xdp_drops: 0
     rx_queue_49_xdp_tx: 0
     rx_queue_49_xdp_tx_errors: 0
     rx_queue_50_xdp_packets: 0
     rx_queue_50_xdp_bytes: 0
     rx_queue_50_drops: 0
     rx_queue_50_xdp_redirect: 0
     rx_queue_50_xdp_drops: 0
     rx_queue_50_xdp_tx: 0
     rx_queue_50_xdp_tx_errors: 0
     rx_queue_51_xdp_packets: 0
     rx_queue_51_xdp_bytes: 0
     rx_queue_51_drops: 0
     rx_queue_51_xdp_redirect: 0
     rx_queue_51_xdp_drops: 0
     rx_queue_51_xdp_tx: 0
     rx_queue_51_xdp_tx_errors: 0
     rx_queue_52_xdp_packets: 0
     rx_queue_52_xdp_bytes: 0
     rx_queue_52_drops: 0
     rx_queue_52_xdp_redirect: 0
     rx_queue_52_xdp_drops: 0
     rx_queue_52_xdp_tx: 0
     rx_queue_52_xdp_tx_errors: 0
     rx_queue_53_xdp_packets: 0
     rx_queue_53_xdp_bytes: 0
     rx_queue_53_drops: 0
     rx_queue_53_xdp_redirect: 0
     rx_queue_53_xdp_drops: 0
     rx_queue_53_xdp_tx: 0
     rx_queue_53_xdp_tx_errors: 0
     rx_queue_54_xdp_packets: 0
     rx_queue_54_xdp_bytes: 0
     rx_queue_54_drops: 0
     rx_queue_54_xdp_redirect: 0
     rx_queue_54_xdp_drops: 0
     rx_queue_54_xdp_tx: 0
     rx_queue_54_xdp_tx_errors: 0
     rx_queue_55_xdp_packets: 0
     rx_queue_55_xdp_bytes: 0
     rx_queue_55_drops: 0
     rx_queue_55_xdp_redirect: 0
     rx_queue_55_xdp_drops: 0
     rx_queue_55_xdp_tx: 0
     rx_queue_55_xdp_tx_errors: 0
     rx_queue_56_xdp_packets: 0
     rx_queue_56_xdp_bytes: 0
     rx_queue_56_drops: 0
     rx_queue_56_xdp_redirect: 0
     rx_queue_56_xdp_drops: 0
     rx_queue_56_xdp_tx: 0
     rx_queue_56_xdp_tx_errors: 0
     rx_queue_57_xdp_packets: 0
     rx_queue_57_xdp_bytes: 0
     rx_queue_57_drops: 0
     rx_queue_57_xdp_redirect: 0
     rx_queue_57_xdp_drops: 0
     rx_queue_57_xdp_tx: 0
     rx_queue_57_xdp_tx_errors: 0
     rx_queue_58_xdp_packets: 0
     rx_queue_58_xdp_bytes: 0
     rx_queue_58_drops: 0
     rx_queue_58_xdp_redirect: 0
     rx_queue_58_xdp_drops: 0
     rx_queue_58_xdp_tx: 0
     rx_queue_58_xdp_tx_errors: 0
     rx_queue_59_xdp_packets: 0
     rx_queue_59_xdp_bytes: 0
     rx_queue_59_drops: 0
     rx_queue_59_xdp_redirect: 0
     rx_queue_59_xdp_drops: 0
     rx_queue_59_xdp_tx: 0
     rx_queue_59_xdp_tx_errors: 0
     rx_queue_60_xdp_packets: 0
     rx_queue_60_xdp_bytes: 0
     rx_queue_60_drops: 0
     rx_queue_60_xdp_redirect: 0
     rx_queue_60_xdp_drops: 0
     rx_queue_60_xdp_tx: 0
     rx_queue_60_xdp_tx_errors: 0
     rx_queue_61_xdp_packets: 0
     rx_queue_61_xdp_bytes: 0
     rx_queue_61_drops: 0
     rx_queue_61_xdp_redirect: 0
     rx_queue_61_xdp_drops: 0
     rx_queue_61_xdp_tx: 0
     rx_queue_61_xdp_tx_errors: 0
     rx_queue_62_xdp_packets: 0
     rx_queue_62_xdp_bytes: 0
     rx_queue_62_drops: 0
     rx_queue_62_xdp_redirect: 0
     rx_queue_62_xdp_drops: 0
     rx_queue_62_xdp_tx: 0
     rx_queue_62_xdp_tx_errors: 0
     rx_queue_63_xdp_packets: 0
     rx_queue_63_xdp_bytes: 0
     rx_queue_63_drops: 0
     rx_queue_63_xdp_redirect: 0
     rx_queue_63_xdp_drops: 0
     rx_queue_63_xdp_tx: 0
     rx_queue_63_xdp_tx_errors: 0
     tx_queue_0_xdp_xmit: 0
     tx_queue_0_xdp_xmit_errors: 0
"""
    d1_start = pluginValidateOffload.ethtool_stat_parse(data1_start)
    assert isinstance(d1_start, dict)
    assert d1_start["rx_queue_61_xdp_bytes"] == "0"

    d2_start = pluginValidateOffload.ethtool_stat_parse(data2_start)
    assert isinstance(d2_start, dict)
    assert d2_start["rx_queue_61_xdp_bytes"] == "0"

    d1_end = pluginValidateOffload.ethtool_stat_parse(data1_end)
    assert isinstance(d1_end, dict)

    d2_end = pluginValidateOffload.ethtool_stat_parse(data2_end)
    assert isinstance(d2_end, dict)

    v = pluginValidateOffload.ethtool_stat_get_packets(d1_start, "rx")
    assert v == 7
    v = pluginValidateOffload.ethtool_stat_get_packets(d1_start, "tx")
    assert v is None

    res1: dict[str, int] = {}
    assert pluginValidateOffload.ethtool_stat_get_startend(res1, data1_start, "start")
    assert res1 == {
        "rx_start": 7,
    }
    assert pluginValidateOffload.ethtool_stat_get_startend(res1, data1_end, "end")
    assert res1 == {
        "rx_start": 7,
        "rx_end": 7,
    }

    res2: dict[str, int] = {}
    assert pluginValidateOffload.ethtool_stat_get_startend(res2, data2_start, "start")
    assert res2 == {
        "rx_start": 7,
    }
    assert pluginValidateOffload.ethtool_stat_get_startend(res2, data2_end, "end")
    assert res2 == {
        "rx_start": 7,
        "rx_end": 7,
    }
