FROM quay.io/centos/centos:stream9

RUN curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable:cri-o:1.26.1.repo https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:1.26.1/CentOS_9_Stream/devel:kubic:libcontainers:stable:cri-o:1.26.1.repo

RUN curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_9_Stream/devel:kubic:libcontainers:stable.repo


RUN INSTALL_PKGS="vim wget jq python3 git cri-tools net-tools iptables iproute pciutils ethtool httpd iperf3 tcpdump sysstat ipmitool util-linux" && yum install -y ${INSTALL_PKGS}

CMD ["/bin/bash"]
